seed: 0
hid: [64, 64, 64]
n_steps: 1000000
replay_size: 1000000
gamma: 0.99
tau: 0.005
lr: 0.0005
batch_size: 128
start_steps: 1000
update_every: 1
gradient_steps: -1
action_noise: null
ent_coef: auto_0.2
target_entropy: auto
use_sde: false
sde_sample_freq: -1
target_update_interval: 1
use_sde_at_warmup: false
num_test_episodes: 500
max_ep_len: 200
save_freq: 10
test_only: false
load_episode: -1
run_id: -1
log_interval: 10
eval_freq: 10000
n_eval_episodes: 1