actor_lr: 3e-4
critic_lr: 3e-4
temp_lr: 3e-4
hidden_dims: [256, 256]
discount: 0.99
tau: 0.005
num_qs: 3
num_min_qs: null
critic_dropout_rate: 0.002
critic_layer_norm: false
target_entropy: -1
init_temperature: 0.1
sampled_backup: true
buffer_size: 1000000
use_her: true
n_her_samples: 4
goal_selection_strategy: future
handle_timeout_termination: true
start_steps: 2000
batch_size: 64
utd_ratio: 10
squash_output: True
